### ISSUE TITLE
Update gatsby-theme-apollo-core colors with Hummingbot brand color

### ISSUE THREAD

**Issue by mirshko** [CoinAlpha/hummingbot-docs#2]
It seems that its not possible to use a non-Apollo SpaceKit primary & secondary color as the colors depend on a function that pulls different shades of the color for hover states for certain areas. Some work arounds would be: A. Fork space-kit and add the hummingbot theme colors and use that, fork space-kit, apollo-core, apollo-docs, and create a gatsby-theme-hummingbot-docs project that this repo then uses on its own. One is a quick win, one is probably more scalable.

**Comment by dennisocana** [comment]
I will discuss with @carlolm tomorrow about this story and close if needed.

**Comment by carlolm** [comment]
There isn't much color on the site.  Actually adding the admonitions will add a lot more color.

https://app.clubhouse.io/coinalpha/story/11825/styling-of-admonitions-call-outs-for-documentation-site

Antonio has already come up with a new design / color scheme for that:
https://www.figma.com/file/gq0MwHcJoGnkoxlS4exWiG/HB-Call-outs-Restyle?node-id=0%3A1

**Comment by dennisocana** [comment]
Closing w.r.t. the Clubhouse story.
