### ISSUE TITLE
Create new liquidity mining quickstart guide

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot-docs#296]
(This story is actually for the private hummingbot-io repo)

# Why

We want new users to have a good experience running Hummingbot and earning rewards with liquidity mining. Currently there's a regular [quickstart guide](https://hummingbot.io/academy/quickstart/) along with a [liquidty mining guide](https://hummingbot.io/academy/liquidity-mining/). These are redundant and can be replaced with an updated, simpler guide.

# What

Following the script of [this video](https://youtu.be/ME5osB8sX_s), create a new version of liquidity mining quickstart guide with the following general steps:
1. Create API keys
2. Add read-only API key to Miner
3. Install Hummingbot (macOS or Windows installer)
4. Add trade API key to Hummingbot
5. Run bot and see rewards on Miner

I suggest making this a single, lengthy guide for now. Afterwards, we can decide whether to break it up or not.

# More notes

@continuitydrift Per this morning's meeting, here are more notes to help you with this task:
- This is a new tutorial-type doc that eventually replaces the existing "Getting started" guide
- For each step above, create a separate folder in the `/content/guide` folder of https://github.com/coinalpha/hummingbot-io
- Look at the other guides in that folder for inspiration, and follow a similar style
- For each step, add the context needed for users to understand what they're doing, but don't try to explain everything since this is a tutorial aimed at the average new user
- Don't worry about stitching the various steps together yet. After you have finished, we'll create something similar to this page that combines the steps into a single page like https://hummingbot.io/academy/quickstart/

**Comment by continuitydrift** [comment]
I've started creating a new .mdx file, with the five general steps, following the video!

**Comment by ralphemersonic** [comment]
Do we need to include this in the documentation roadmap?
