### ISSUE TITLE
bot did not insert further short orders and did not update the prices of the long orders 

### ISSUE THREAD

**Issue by foxxcrypto** [CoinAlpha/hummingbot-docs#300]
After five short trades were open, no more were entered on the short side and five long orders remained active on the long side but were no longer updated with the correct spread.

thanks. bye.
[logs_conf_perpetual_market_making_1.zip](https://github.com/CoinAlpha/hummingbot-docs/files/6142719/logs_conf_perpetual_market_making_1.zip)

**Comment by JeremyKono** [comment]
Please create the issue here, this is solely for documentation: https://github.com/CoinAlpha/hummingbot
