### ISSUE TITLE
URLs/links with #anchor tags are being blocked by the search bar

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot-docs#39]
Here's an example:
https://docs.hummingbot.io/strategies/balancer-arb/#amm-arbitrage-strategy

# Current behavior

![image](https://user-images.githubusercontent.com/12274903/98862610-0a92a900-241c-11eb-87fa-ed14a80be23a.png)

# Desired behavior

![image](https://user-images.githubusercontent.com/12274903/98862783-4f1e4480-241c-11eb-8885-1c4dd23eabe7.png)

@thomasyit can you research how to fix this?

**Comment by thomasyit** [comment]
done
