### ISSUE TITLE
Is Hummingbot similar to Grid Trading Bot?

### ISSUE THREAD

**Issue by bromoapp** [CoinAlpha/hummingbot-docs#394]
Hi, I know this may not be an appropriate place to post this question... I really sorry.
But is hummingbot a grid trading bot, like the one discussed in [**this** ](https://hackernoon.com/wtf-is-a-grid-trading-bot-em4v3ytm) article?

Thank you

**Comment by geloadviento** [comment]
Hi! @bromoapp, Hummingbot is not similar to Grid Trading Bot. Hummingbot runs on different strategies and if your interested on using Hummingbot we currently have a pre-set script available to be used that works somewhat the same as a Grid Trade Strategy. Do note that if your looking forward to use the TWAP Strategy this is only compatible on Hummingbot Source Build.

Here are the list of our current strategies: https://docs.hummingbot.io/strategies/overview/
Here's the link to our TWAP Strategy: https://docs.hummingbot.io/developer/twap/#gatsby-focus-wrapper
Here's the link on how to install Hummingbot Source depending on your Operating System: https://docs.hummingbot.io/installation/overview/
