### ISSUE TITLE
Order_amount not working on spot perp arb

### ISSUE THREAD

**Issue by Ebunfx12** [CoinAlpha/hummingbot-docs#477]
Hello. The order_amount on spot_perpetual arbitrage bot only makes effect for perpetual. It doesn’t reflect for spot trading I.e my order_amount is 1 UNFI however the bot is only placing a sell order of 1UNFI for perpetual. On Spot, it is placing a 0 UNFI buy trade which isn’t making the trade go through. Please look into it, thank you

**Comment by dennisocana** [comment]
@Ebunfx12 thanks for the feedback. This repository is for the hummingbot documentation. Please post the issue in the main repository https://github.com/CoinAlpha/hummingbot/issues and create a bug ticket. Also provide complete information such as log files, configs and screenshots so we can better investigate a fix.
